version: '3.7'

services:
  front:
    image: node:18.3-alpine
    user: node
    ports:
      - 24678:3000 # 3000:3000となっていると、HMRが走らない。 https://github.com/nuxt/nuxt/issues/12748#issuecomment-1397234516
    volumes:
      - ./:/project
    working_dir: /project
    command: [ npm, run, dev ]
